### ISSUE TITLE
[FR] Add automation template in documentation

### ISSUE THREAD

**Issue by Lockszmith-GH** [ikifar2012/addons.mathesonsteplock.ca#2]
For the noobs (like me), add a suggestion to add an automation to allow automatic backup creation.

This is what I am using:
```yaml
alias: Automatic Remote Backup
description: 'Upon sunrise, create a remote backup'
trigger:
  - platform: sun
    event: sunrise
    offset: '0'
condition: []
action:
  - service: hassio.addon_start
    data:
      addon: 3490a758_remote_backup
mode: single
```
